services:
  mysql:
    image : mysql:5.7
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "/home/yinyunlong/person/program/mysql/conf:/etc/mysql/conf.d"
      - "/home/yinyunlong/person/program/mysql/logs:/logs"
      - "/home/yinyunlong/person/program/mysql/data:/var/lib/mysql"
    networks:
      - powerjobnet
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=powerjob-daily"
      - "TZ=Asia/Shanghai"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=root" ]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 5s


  server_web:
    image: powerjob-server:v1
    deploy:
      resources:
        limits:
          memory: 1024M
    container_name: powerjob_server
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - powerjobnet
#    links:
#      - mysql_db:sql_db
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:7700/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      PARAMS : ""
      JVMOPTIONS : "Xmx512m"
    ports:
      - 7700:7700
      - 10086:10086
      - 5001:5005
      - 10001:10000
    volumes:
      - "/home/yinyunlong/powerjob/server:/root/powerjob/server"
    entrypoint: ["sh","-c","java $JVMOPTIONS -jar /powerjob-server.jar $PARAMS"]

  worker_web:
    image: powerjob_work_python:v1
    depends_on:
      server_web:
        condition: service_healthy
    container_name: powerjob_work
    networks:
      - powerjobnet
#    links:
#      - powerjob_server:power_server
    restart: always
    ports:
      - 27000:27000
    volumes:
      - "/home/yinyunlong/.config/clash/:/home/yinyunlong/.config/clash/"
      - "/home/yinyunlong/person/python_workspace/powerjob-work-python/resource/:/home/yinyunlong/person/python_workspace/powerjob-work-python/resource/"
      - "/home/yinyunlong/person/python_workspace/powerjob-work-python/src/task/:/home/yinyunlong/person/python_workspace/powerjob-work-python/src/task/"
    entrypoint: [ "python", "/home/powerjob-work-python/powerjob_worker.py" ]


networks:
    powerjobnet:
        name: powerjobnet
        driver: bridge